language: C java
install: make cmake valgrind
compiler:
 - gcc
script:
 - cmake -DSANITIZE_ADDRESS=On -DSANITIZE_UNDEFINED=On -DCMAKE_BUILD_TYPE=Debug .
 - make
 - make test
 - gcov src/CMakeFiles/salt.dir/salt.c.gcno src/CMakeFiles/salt.dir/salti_handshake.c.gcno src/CMakeFiles/salt.dir/salti_util.c.gcno
 - rm CMakeCache.txt
 - sh valgrind.sh
 - sh test_echo_with_java.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)